### ISSUE TITLE
ignorecase should probably be ignored

### ISSUE THREAD

**Issue by LemonBoy** [tommcdo/vim-lion#21]
Take something like the following snippet

```
foo-bar  Baz 
foo-car Baz
```

If `ignorecase` is on and I select `B` as alignment char the plugin uses both `b` and `B` as alignment points which isn't quite what I asked for since I went the extra mile to press b *and* the shift key.

**Comment by qstrahl** [comment]
If `ignorecase` is on and you select `b`, should it align on `b` and `B`?

**Comment by LemonBoy** [comment]
I'd expect it to use `b` only. The way to go IMO is to document this behaviour and offer a way to toggle the case-sensitivity that's independent from `ignorecase`.

**Comment by tommcdo** [comment]
Yeah, I agree that it should disregard `'ignorecase'` and use a case-sensitive match. Aligning by alphabetic characters is probably a pretty rare case to start, so if it needs to be done with case ignored, a pattern alignment can be used (e.g. `glip/\cb`).

It may be tricky to accomplish, though, since the implementation uses `match()`, which observes `'ignorecase'`. A workaround may be to capture, set, and restore the setting during alignment. I'd prefer not to if possible.

**Comment by qstrahl** [comment]
@tommcdo You can add `\C` to the pattern passed to `match()`

**Comment by LemonBoy** [comment]
I confirm that adding a `\C` in front of the pattern solves this problem.
